version: "3.9"

services:
  # üêò Base de datos PostgreSQL local
  postgres:
    image: postgres:15-alpine
    container_name: finwise-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: doadmin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: defaultdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # üîê Microservicio de autenticaci√≥n
  auth-service:
    build: .
    container_name: finwise-auth-service
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      # Conexi√≥n local dentro del docker network
      DATABASE_URL: postgres://doadmin:root@postgres:5432/defaultdb
      JWT_SECRET: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6IjY0MGJjMWViOGU3MjI2Mjc4MDg4OTlhNmI3OTFhNDhmIn0.eyJ1c2VySWQiOiJNaWNhZWwiLCJwZXJtaXNzaW9ucyI6ImFkbWluIiwiYXV0aG9yaXphdGlvbiI6ImRrc2xhZmprbHNkYWpmZHNmIn0.ZpNcIaMIzvZl0i5GwSIkBOBHcF3tJctEuCrBPD6kEyKEqIcoIhZkZRqUJgXHrpsV-hitSNKx0GVbn6ZlGeBHWg
      PORT: 5000

volumes:
  postgres_data:
